export const students = [
  {
    student_name: 'Stefano Paredes',
    end_date: '2025-02-28',
    days: 'M,J',
    start_time: '13:00',
    end_time: '14:00',
    email: 'adrianamc_6@hotmail.com',
    student_dni: '79619651',
    parent_name: 'Adriana Ponce Yovera',
  },
  {
    student_name: 'Sofia Paredes',
    end_date: '2025-02-28',
    days: 'M,J',
    start_time: '13:00',
    end_time: '14:00',
    email: 'adrianamc_6@hotmail.com',
    student_dni: '92526773',
    parent_name: 'Adriana Ponce Yovera',
  },
  {
    student_name: 'Nyha Maldonado',
    end_date: '',
    days: 'M,J',
    start_time: '13:00',
    end_time: '14:00',
    email: 'amaldonadocerna@gmail.com',
    student_dni: '90307148',
    parent_name: 'Abraham Maldonado Cerna',
  },
  {
    student_name: 'Alvaro Josue Avendaño Rodriguez',
    end_date: '',
    days: 'M,J',
    start_time: '14:00',
    end_time: '15:00',
    email: 'azucenarodriguezen@gmail.com',
    student_dni: '92408023',
    parent_name: 'Azucena Rodríguez Encarnaciòn',
  },
  {
    student_name: 'Matteo Cruzado',
    end_date: '',
    days: 'L,X,V',
    start_time: '14:00',
    end_time: '15:00',
    email: 'betsabet180@gmail.com',
    student_dni: '72901833',
    parent_name: 'Betsabet Tapia',
  },
  {
    student_name: 'Nihal Rojas',
    end_date: '',
    days: 'M,J',
    start_time: '13:00',
    end_time: '14:00',
    email: 'beyitnihal2331@gmail.com',
    student_dni: '79001026',
    parent_name: 'Esther j. Yupanqui Laura',
  },
  {
    student_name: 'Varun Bustos',
    end_date: '',
    days: 'M,J',
    start_time: '13:00',
    end_time: '14:00',
    email: 'brendiiz2204@gmail.com',
    student_dni: '90673840',
    parent_name: 'Brenda Tasayco Huamán',
  },
  {
    student_name: 'Rafaela Bustos',
    end_date: '',
    days: 'M,J',
    start_time: '13:00',
    end_time: '14:00',
    email: 'brendiiz2204@gmail.com',
    student_dni: '90673840',
    parent_name: 'Brenda Tasayco Huamán',
  },
  {
    student_name: 'Luka Cachai Mori',
    end_date: '',
    days: 'L,X,V',
    start_time: '13:00',
    end_time: '14:00',
    email: 'cachaymauro7@gmail.com',
    student_dni: '81854636',
    parent_name: 'Paula Mori Pizango',
  },
  {
    student_name: 'Lua Cuenca Peralta',
    end_date: '',
    days: 'D',
    start_time: '13:15',
    end_time: '14:00',
    email: 'carlosmauriciocuencarios@gmail.com',
    student_dni: '93183384',
    parent_name: 'Carlos Mauricio Cuenca Rios',
  },
  {
    student_name: 'Elieth Quispe',
    end_date: '',
    days: 'L,X,V',
    start_time: '13:00',
    end_time: '14:00',
    email: 'carulisseth@gmail.com',
    student_dni: '91436306',
    parent_name: 'Lisseth Carrera Ruiz',
  },
  {
    student_name: 'Ania Quispe',
    end_date: '',
    days: 'L,X,V',
    start_time: '13:00',
    end_time: '14:00',
    email: 'carulisseth@gmail.com',
    student_dni: '92629507',
    parent_name: 'Lisseth Carrera Ruiz',
  },
  {
    student_name: 'Brian Ygnacio',
    end_date: '',
    days: 'L,M,X,J,V',
    start_time: '18:00',
    end_time: '19:00',
    email: 'cedith22@hotmail.com',
    student_dni: '78476016',
    parent_name: 'Celia Ramírez Luna',
  },
  {
    student_name: 'Gabriel Ygnacio',
    end_date: '',
    days: 'L,M,X,J,V',
    start_time: '18:00',
    end_time: '19:00',
    email: 'cedith22@hotmail.com',
    student_dni: '79259552',
    parent_name: 'Celia Ramírez Luna',
  },
  {
    student_name: 'Leonardo Huaman',
    end_date: '',
    days: 'L,M,X,J,V',
    start_time: '19:00',
    end_time: '20:00',
    email: 'claudiapaola.13@gmail.com',
    student_dni: '75043791',
    parent_name: 'Claudia Rubio Rojas',
  },
  {
    student_name: 'Carolina Pintado Ramos',
    end_date: '2025-02-28',
    days: 'L,X,V',
    start_time: '13:00',
    end_time: '14:00',
    email: 'claudiapaolar37@gmail.com',
    student_dni: '78336548',
    parent_name: 'Claudia Ramos Caycho',
  },
  {
    student_name: 'Facundo Serra Manrique',
    end_date: '2025-02-28',
    days: 'L,X,V',
    start_time: '13:00',
    end_time: '14:00',
    email: 'claupim8014@gmail.com',
    student_dni: '79452442',
    parent_name: 'Jose Luis Serra Garcia',
  },
  {
    student_name: 'Gerardo Mercado',
    end_date: '',
    days: 'D',
    start_time: '13:00',
    end_time: '15:00',
    email: 'crikme84@gmail.com',
    student_dni: '90797616',
    parent_name: 'Erik Mercado',
  },
  {
    student_name: 'Fernanda Mercado',
    end_date: '',
    days: 'D',
    start_time: '13:00',
    end_time: '15:00',
    email: 'crikme84@gmail.com',
    student_dni: '78757795',
    parent_name: 'Erik Mercado',
  },
  {
    student_name: 'Haydé Guzmán',
    end_date: '',
    days: 'D',
    start_time: '13:00',
    end_time: '15:00',
    email: 'crikme84@gmail.com',
    student_dni: '41233386',
    parent_name: 'Erik Mercado',
  },
  {
    student_name: 'Joaquin Solorzano Espinoza',
    end_date: '',
    days: 'L,X,V',
    start_time: '13:00',
    end_time: '14:00',
    email: 'cynthiaveranisaespinoza@gmail.com',
    student_dni: '78860677',
    parent_name: 'CYNTHIA VERANISA ESPINOZA QUINTEROS',
  },
  {
    student_name: 'Samuel Vela Cabrera',
    end_date: '',
    days: 'L,X,V',
    start_time: '13:00',
    end_time: '14:00',
    email: 'danielvelaa@gmail.com',
    student_dni: '75046321',
    parent_name: 'Carla Cabrera García',
  },
  {
    student_name: 'Josue Muro Mauricio',
    end_date: '2025-02-28',
    days: 'L,X,V',
    start_time: '14:00',
    end_time: '15:00',
    email: 'dayannem@hotmail.com',
    student_dni: '90554823',
    parent_name: 'DANITZA MAURICIO',
  },
  {
    student_name: 'Diana Sanchez',
    end_date: '',
    days: 'L,X,V',
    start_time: '13:00',
    end_time: '14:00',
    email: 'diana_maryori@hotmail.com',
    student_dni: '79858068',
    parent_name: 'Diana Canchachi',
  },
  {
    student_name: 'Thiago Sanchez',
    end_date: '',
    days: 'L,X,V',
    start_time: '13:00',
    end_time: '14:00',
    email: 'diana_maryori@hotmail.com',
    student_dni: '77750501',
    parent_name: 'Diana Canchachi',
  },
  {
    student_name: 'Daryen Mogollón Alegría',
    end_date: '',
    days: 'L,X,V',
    start_time: '13:00',
    end_time: '14:00',
    email: 'donaao@hotmail.com',
    student_dni: '90301185',
    parent_name: 'Dona Yenli Alegría Otaegui',
  },
  {
    student_name: 'Abigail Cherres',
    end_date: '',
    days: 'M,J',
    start_time: '13:00',
    end_time: '14:00',
    email: 'drojaspimentel@gmail.com',
    student_dni: '78763506',
    parent_name: 'Dayana Rojas Pimentel',
  },
  {
    student_name: 'Nataly Andrade',
    end_date: '2025-02-28',
    days: 'L,X,V',
    start_time: '13:00',
    end_time: '14:00',
    email: 'edithaburtope@gmail.com',
    student_dni: '09911275',
    parent_name: 'Edith Mirian Aburto Perez',
  },
  {
    student_name: 'Sebastián Gálvez Susaya',
    end_date: '',
    days: 'D',
    start_time: '13:00',
    end_time: '15:00',
    email: 'elisu0911@gmail.com',
    student_dni: '79769322',
    parent_name: 'Gaby susaya',
  },
  {
    student_name: 'Gabriel Gálvez Susaya',
    end_date: '',
    days: 'D',
    start_time: '13:00',
    end_time: '15:00',
    email: 'elisu0911@gmail.com',
    student_dni: '78491330',
    parent_name: 'Gaby susaya',
  },
  {
    student_name: 'Raphael Sanchez Pano',
    end_date: '',
    days: 'M,J',
    start_time: '13:00',
    end_time: '14:00',
    email: 'fernandopano@gmail.com',
    student_dni: '91267934',
    parent_name: 'Trinidad Pano',
  },
  {
    student_name: 'Franchesca Huapaya Ticse',
    end_date: '',
    days: 'D',
    start_time: '13:00',
    end_time: '15:00',
    email: 'franchescahuapaya@gmail.com',
    student_dni: '70502507',
    parent_name: 'Ninguno',
  },
  {
    student_name: 'Yul Granjeda',
    end_date: '',
    days: 'L,M,X,J,V',
    start_time: '18:00',
    end_time: '19:00',
    email: 'gamyservice201175@gmail.com',
    student_dni: '77561495',
    parent_name: 'Marisol Almendrades Torrel',
  },
  {
    student_name: 'Manuel Canales',
    end_date: '',
    days: 'L,X,V',
    start_time: '13:00',
    end_time: '14:00',
    email: 'gbarrios_4@hotmail.com',
    student_dni: '78151099',
    parent_name: 'Glenda Barrios',
  },
  {
    student_name: 'Antonia Canales',
    end_date: '',
    days: 'L,X,V',
    start_time: '13:00',
    end_time: '14:00',
    email: 'gbarrios_4@hotmail.com',
    student_dni: '91110702',
    parent_name: 'Glenda Barrios',
  },
  {
    student_name: 'Isabella Crispin del Rosario',
    end_date: '',
    days: 'L,X,V',
    start_time: '13:00',
    end_time: '14:00',
    email: 'giovanajibaja@gmail.com',
    student_dni: '90838381',
    parent_name: 'Giovanna Jibaja Soria',
  },
  {
    student_name: 'Sebastián Ferrer',
    end_date: '',
    days: 'L,X,V',
    start_time: '13:00',
    end_time: '14:00',
    email: 'gloriav.latorre@gmail.com',
    student_dni: '78394022',
    parent_name: 'Victoria La Torre',
  },
  {
    student_name: 'Adrián Peña',
    end_date: '',
    days: 'M,J',
    start_time: '14:00',
    end_time: '15:00',
    email: 'hatmy_18@hotmail.com',
    student_dni: '90012171',
    parent_name: 'Shirley Insa Arrieta',
  },
  {
    student_name: 'Ximena Cornejo Irribarren',
    end_date: '',
    days: 'L,X,V',
    start_time: '13:00',
    end_time: '14:00',
    email: 'irribarrendiana54@gmail.com',
    student_dni: '90461086',
    parent_name: 'Diana Irribarren',
  },
  {
    student_name: 'Mariapaz Cornejo Irribarren',
    end_date: '',
    days: 'L,X,V',
    start_time: '13:00',
    end_time: '14:00',
    email: 'irribarrendiana54@gmail.com',
    student_dni: '91573576',
    parent_name: 'Diana irribarren',
  },
  {
    student_name: 'Liam Javier Noled Rodriguez',
    end_date: '',
    days: 'D',
    start_time: '13:00',
    end_time: '15:00',
    email: 'jackr185@gmail.com',
    student_dni: '91754759',
    parent_name: 'Elvis Nole Rodriguez',
  },
  {
    student_name: 'Nikolas Ramirez',
    end_date: '',
    days: 'L,M,X,J,V',
    start_time: '19:00',
    end_time: '20:00',
    email: 'jannetpautrat@gmail.com',
    student_dni: '25766943',
    parent_name: 'Jannet Pautrat García',
  },
  {
    student_name: 'Olenka Ramirez',
    end_date: '',
    days: 'L,M,X,J,V',
    start_time: '19:00',
    end_time: '20:00',
    email: 'jannetpautrat@gmail.com',
    student_dni: '25766943',
    parent_name: 'Jannet Pautrat García',
  },
  {
    student_name: 'Sofía Castillo Guerrero',
    end_date: '',
    days: 'M,J',
    start_time: '13:00',
    end_time: '14:00',
    email: 'jcca.2511@gmail.com',
    student_dni: '91739507',
    parent_name: 'Amparo Guerrero Quiñones',
  },
  {
    student_name: 'Sofia Cornejo',
    end_date: '',
    days: 'L,M,X,J,V',
    start_time: '18:00',
    end_time: '19:00',
    email: 'jennynietoa@gmail.com',
    student_dni: '77775743',
    parent_name: 'Jenny Nieto',
  },
  {
    student_name: 'Gianella Cornejo',
    end_date: '',
    days: 'L,M,X,J,V',
    start_time: '18:00',
    end_time: '19:00',
    email: 'jennynietoa@gmail.com',
    student_dni: '79319656',
    parent_name: 'Jenny Nieto',
  },
  {
    student_name: 'Valeria Becerra',
    end_date: '2025-02-28',
    days: 'M,J',
    start_time: '13:00',
    end_time: '14:00',
    email: 'jennyvic1111@hotmail.com',
    student_dni: '91502736',
    parent_name: 'Jennifer Esther Ruiz Ruiz',
  },
  {
    student_name: 'Diego Córdova Turpo',
    end_date: '',
    days: 'L,X,V',
    start_time: '13:00',
    end_time: '14:00',
    email: 'jentur2021@gmail.com',
    student_dni: '77940698',
    parent_name: 'Jenny Turpo',
  },
  {
    student_name: 'Yhamil Yaret Chacón Huamani',
    end_date: '2025-02-28',
    days: 'M,J',
    start_time: '14:00',
    end_time: '15:00',
    email: 'jhajaira27013@gmail.com',
    student_dni: '78129982',
    parent_name: 'Jhajaira Huamani Liza',
  },
  {
    student_name: 'Valentina Arteaga',
    end_date: '',
    days: 'D',
    start_time: '13:00',
    end_time: '15:00',
    email: 'joselyn.huallanca.26@gmail.com',
    student_dni: '91877396',
    parent_name: 'Joselyn huallanca mitma',
  },
  {
    student_name: 'Alanna More',
    end_date: '',
    days: 'M,J',
    start_time: '13:00',
    end_time: '14:00',
    email: 'joyce_gb.96@hotmail.com',
    student_dni: '90838326',
    parent_name: 'Joyce García',
  },
  {
    student_name: 'Micaela Suquilanda Hinostroza',
    end_date: '',
    days: 'L,X',
    start_time: '13:00',
    end_time: '14:00',
    email: 'jozz.hc@gmail.com',
    student_dni: '78977611',
    parent_name: 'Josselyn Margarita Jesús Hinostroza Cossio',
  },
  {
    student_name: 'Antonella Carhuas',
    end_date: '',
    days: 'D',
    start_time: '13:15',
    end_time: '14:00',
    email: 'jramirezlaupa@gmail.com',
    student_dni: '77591027',
    parent_name: 'Jessica Ramirez Laupa',
  },
  {
    student_name: 'Sammir Carhuas',
    end_date: '',
    days: 'D',
    start_time: '13:00',
    end_time: '15:00',
    email: 'jramirezlaupa@gmail.com',
    student_dni: '77591027',
    parent_name: 'Jessica Ramirez Laupa',
  },
  {
    student_name: 'Valetska Gonzales Lopez',
    end_date: '2025-02-28',
    days: 'M,J',
    start_time: '13:00',
    end_time: '14:00',
    email: 'jumago221@hotmail.com',
    student_dni: '91528955',
    parent_name: 'Juan Manuel Gonzales Acosta',
  },
  {
    student_name: 'Bruno Vega Chipana',
    end_date: '',
    days: 'L,X,V',
    start_time: '13:00',
    end_time: '14:00',
    email: 'kathy.chipana36@gmail.con',
    student_dni: '90247488',
    parent_name: 'Kathy CHIPANA',
  },
  {
    student_name: 'Dominic Ygnacio Pagara',
    end_date: '',
    days: 'L,M,X,J,V',
    start_time: '18:00',
    end_time: '19:00',
    email: 'kathy030705@gmail.com',
    student_dni: '78310958',
    parent_name: 'María Milagros Purizaca Castillo',
  },
  {
    student_name: 'Gisel Cupe Miranda',
    end_date: '',
    days: 'L,X,V',
    start_time: '14:00',
    end_time: '15:00',
    email: 'lcupeto33@gmail.com',
    student_dni: '43134342',
    parent_name: 'Luis Favio Cupe Torres',
  },
  {
    student_name: 'Thiago Sebastian Zavala Espinoza',
    end_date: '',
    days: 'L,X',
    start_time: '13:00',
    end_time: '14:00',
    email: 'lizeq2207@gmail.com',
    student_dni: '78182817',
    parent_name: 'Lizbeth Espinoza',
  },
  {
    student_name: 'Camilo Flores',
    end_date: '',
    days: 'D',
    start_time: '13:00',
    end_time: '15:00',
    email: 'lriverav84@gmail.com',
    student_dni: '92312162',
    parent_name: 'Liz Rivera Valverde y Carlos Flores',
  },
  {
    student_name: 'Lucyana Martinez Valdez',
    end_date: '2025-02-28',
    days: 'L,X,V',
    start_time: '14:00',
    end_time: '15:00',
    email: 'lucyanabelvaldez@gmail.com',
    student_dni: '91659258',
    parent_name: 'Lucy Valdez Romero',
  },
  {
    student_name: 'Fabrizio Montalvo',
    end_date: '',
    days: 'L,M,X,J,V',
    start_time: '19:00',
    end_time: '20:00',
    email: 'marthacordovameza@gmail.com',
    student_dni: '41493058',
    parent_name: 'Martha Cordova Meza',
  },
  {
    student_name: 'Max Ponce Delgado',
    end_date: '',
    days: 'L,X,V',
    start_time: '13:00',
    end_time: '14:00',
    email: 'mayra.1.elyzabeth@gmail.com',
    student_dni: '79630473',
    parent_name: 'Mayra delgado',
  },
  {
    student_name: 'Josueh Barrientos Echenique',
    end_date: '2025-02-28',
    days: 'L,X,V',
    start_time: '14:00',
    end_time: '15:00',
    email: 'mbarrientos.xdb@gmail.com',
    student_dni: '91104304',
    parent_name: 'ANGELA XIMENA ECHENIQUE CALI',
  },
  {
    student_name: 'Ariana Arroyo Campos',
    end_date: '',
    days: 'L,X,V',
    start_time: '18:00',
    end_time: '19:00',
    email: 'mijailac@gmail.com',
    student_dni: '91619313',
    parent_name: 'Mijail Arroyo Campos',
  },
  {
    student_name: 'Dylan Jesús Pérez Abriojo',
    end_date: '2025-02-28',
    days: 'M,J',
    start_time: '13:00',
    end_time: '14:00',
    email: 'milagrosabriojo41@gmail.com',
    student_dni: '79620490',
    parent_name: 'Milagros Abriojo Lozano',
  },
  {
    student_name: 'Gianfranco Abanto Rodriguez',
    end_date: '',
    days: 'M,J',
    start_time: '13:00',
    end_time: '14:00',
    email: 'milagrosrodrigueztorres11@gmail.com',
    student_dni: '91328805',
    parent_name: 'Milagros Rodríguez torres',
  },
  {
    student_name: 'Santiago Abanto Rodriguez',
    end_date: '',
    days: 'M,J',
    start_time: '13:00',
    end_time: '14:00',
    email: 'milagrosrodrigueztorres11@gmail.com',
    student_dni: '90128715',
    parent_name: 'Jaime Abanto Rodríguez',
  },
  {
    student_name: 'Valentino  Diaz',
    end_date: '',
    days: 'L,M,X,J,V',
    start_time: '18:00',
    end_time: '19:00',
    email: 'mishel1523@hotmail.com',
    student_dni: '70065938',
    parent_name: 'Tania Cachique Ruiz',
  },
  {
    student_name: 'Joaquin Diaz',
    end_date: '',
    days: 'L,X,V',
    start_time: '14:00',
    end_time: '15:00',
    email: 'mishel1523@hotmail.com',
    student_dni: '70065938',
    parent_name: 'Tania Cachique Ruiz',
  },
  {
    student_name: 'Zoe Danielis',
    end_date: '',
    days: 'L,X,V',
    start_time: '14:00',
    end_time: '15:00',
    email: 'mishel1523@hotmail.com',
    student_dni: '70065938',
    parent_name: 'Tania Cachique Ruiz',
  },
  {
    student_name: 'Hugo Molina',
    end_date: '',
    days: 'L,X,V',
    start_time: '13:00',
    end_time: '14:00',
    email: 'molinanh3@hotmail.com',
    student_dni: '79529717',
    parent_name: 'Jessica Canales Rivadeneyra',
  },
  {
    student_name: 'Luciana Suarez Rodriguez',
    end_date: '2025-02-28',
    days: 'L,X,V',
    start_time: '14:00',
    end_time: '15:00',
    email: 'monicarodriguez611@gmail.com',
    student_dni: '90036436',
    parent_name: 'Mónica Rodríguez',
  },
  {
    student_name: 'Jaiyly Ulloa',
    end_date: '',
    days: 'L,X,V',
    start_time: '13:00',
    end_time: '14:00',
    email: 'mvanessa.ching@gmail.com',
    student_dni: '79966584',
    parent_name: 'Vanessa Ching',
  },
  {
    student_name: 'Yijie Ulloa',
    end_date: '',
    days: 'L,X,V',
    start_time: '13:00',
    end_time: '14:00',
    email: 'mvanessa.ching@gmail.com',
    student_dni: '91044708',
    parent_name: 'Vanessa Ching',
  },
  {
    student_name: 'Cayetana Thais Diaz Aquino',
    end_date: '',
    days: 'L,X,V',
    start_time: '13:00',
    end_time: '14:00',
    email: 'nei.ra24.n@gmail.com',
    student_dni: '45315909',
    parent_name: 'Noelia Aquino Bonilla',
  },
  {
    student_name: 'Nereyda Talavera',
    end_date: '',
    days: 'D',
    start_time: '13:00',
    end_time: '15:00',
    email: 'nereyda.talavera1@gmail.com',
    student_dni: '42268437',
    parent_name: 'Ninguno',
  },
  {
    student_name: 'Ian Chavez Huanzo',
    end_date: '',
    days: 'L,X,V',
    start_time: '14:00',
    end_time: '15:00',
    email: 'nvhm_lady@hotmail.com',
    student_dni: '81612297',
    parent_name: 'María Esther Morveli Pomalla',
  },
  {
    student_name: 'Gaetana Ore Garcia',
    end_date: '2025-02-28',
    days: 'L,X,V',
    start_time: '13:00',
    end_time: '14:00',
    email: 'ore.skydive@gmail.com',
    student_dni: '90948621',
    parent_name: 'ALEXHA GARCÍA TELLO',
  },
  {
    student_name: 'Fabiano Gomez Cabrera',
    end_date: '',
    days: 'X,V',
    start_time: '14:00',
    end_time: '15:00',
    email: 'pecv.cvaldiviesoa@gmail.com',
    student_dni: '46800233',
    parent_name: 'Patricia Cabrera Valdivieso',
  },
  {
    student_name: 'Fabián Mateo Monteza Cachay',
    end_date: '2025-02-28',
    days: 'L,X,V',
    start_time: '14:00',
    end_time: '15:00',
    email: 'perezestrella050@gmail.com',
    student_dni: '91502429',
    parent_name: 'Estrella Cachay Pérez',
  },
  {
    student_name: 'Ethan Anicama Agasajando',
    end_date: '',
    days: 'M,J',
    start_time: '13:00',
    end_time: '14:00',
    email: 'pilar.fasanando@gmail.com',
    student_dni: '91830382',
    parent_name: 'Pilar Fasanando Tapullima',
  },
  {
    student_name: 'Luis Huapaya',
    end_date: '',
    days: 'L,M,X,J,V',
    start_time: '18:00',
    end_time: '19:00',
    email: 'rbksea@gmail.com',
    student_dni: '77643599',
    parent_name: 'Rebeca Enriquez Albornoz',
  },
  {
    student_name: 'Khanum Cabrera',
    end_date: '',
    days: 'M,D',
    start_time: '13:00',
    end_time: '14:00',
    email: 'rebeca_bp@hotmail.com',
    student_dni: '90428061',
    parent_name: 'Rebeca Bedriñana Peralta',
  },
  {
    student_name: 'Alejandro de la Cruz Tapia',
    end_date: '',
    days: 'L,X,V',
    start_time: '14:00',
    end_time: '15:00',
    email: 'risco21182@gmail.com',
    student_dni: '79691731',
    parent_name: 'Leslie Tapia Risco',
  },
  {
    student_name: 'Adrian Laupa',
    end_date: '',
    days: 'L,X,V',
    start_time: '18:00',
    end_time: '19:00',
    email: 'roger.laupa@fremet.com.pe',
    student_dni: '78062088',
    parent_name: 'Roger Laupa',
  },
  {
    student_name: 'Roma Laupa',
    end_date: '',
    days: 'D',
    start_time: '13:15',
    end_time: '14:00',
    email: 'roger.laupa@fremet.com.pe',
    student_dni: '91267675',
    parent_name: 'ROGER LAUPA',
  },
  {
    student_name: 'Samuel Mateo Rojas',
    end_date: '',
    days: 'L,X,V',
    start_time: '13:00',
    end_time: '14:00',
    email: 'rojasmacedosamuelmateo@gmail.com',
    student_dni: '74342205',
    parent_name: 'Elizabeth Macedo Requena',
  },
  {
    student_name: 'Rosemberg Jacob Reategui Espichan',
    end_date: '2025-02-28',
    days: 'L,X,V',
    start_time: '13:00',
    end_time: '14:00',
    email: 'rore147@gmail.com',
    student_dni: '90949620',
    parent_name: 'Aldryn Reategui',
  },
  {
    student_name: 'Abby Pedraza',
    end_date: '2025-02-28',
    days: 'L,X,V',
    start_time: '14:00',
    end_time: '15:00',
    email: 'ruthpb21@gmail.com',
    student_dni: '79266042',
    parent_name: 'Ruth Bustamante Bernal de Pedraza',
  },
  {
    student_name: 'Irma Garcia',
    end_date: '',
    days: 'L,M,X,J,V',
    start_time: '19:00',
    end_time: '20:00',
    email: 'rzavala0805@gmail.com',
    student_dni: '77721739',
    parent_name: 'Rosa Zavala Aybar',
  },
  {
    student_name: 'Aitana Cajas',
    end_date: '',
    days: 'L,M,X,J,V',
    start_time: '18:00',
    end_time: '19:00',
    email: 'sallyhr1506@gmail.com',
    student_dni: '79987465',
    parent_name: 'Sally Hernandez Ramls',
  },
  {
    student_name: 'Valentina Laura Trillo',
    end_date: '2025-02-28',
    days: 'M,J',
    start_time: '13:00',
    end_time: '14:00',
    email: 'sandrag_21_7@hotmail.com',
    student_dni: '41994351',
    parent_name: 'Sandra catalina Lopez torrez',
  },
  {
    student_name: 'Javier Huaroto',
    end_date: '',
    days: 'D',
    start_time: '13:15',
    end_time: '14:00',
    email: 'sandris_1023@hotmail.com',
    student_dni: '93091406',
    parent_name: 'Diego Miguel Huaroto Larrea',
  },
  {
    student_name: 'Lexa Gutierrez Iriarte',
    end_date: '',
    days: 'L,X',
    start_time: '14:00',
    end_time: '15:00',
    email: 'selma.iriarte@gmail.com',
    student_dni: '91630079',
    parent_name: 'Selma Iriarte García',
  },
  {
    student_name: 'Santiago Arenas',
    end_date: '',
    days: 'L,X,V',
    start_time: '14:00',
    end_time: '15:00',
    email: 'sofiaa.arenass.05@gmail.com',
    student_dni: '81852925',
    parent_name: 'Zila Avida Cosme Delgadillo',
  },
  {
    student_name: 'Samuel Lazaro de la Cruz',
    end_date: '',
    days: 'L,X,V',
    start_time: '14:00',
    end_time: '15:00',
    email: 'stephaniedelacruz832@gmail.com',
    student_dni: '91496820',
    parent_name: 'Stephanie De La Cruz',
  },
  {
    student_name: 'Maria Jose Suquilanda Hinostroza',
    end_date: '',
    days: 'L,X',
    start_time: '13:00',
    end_time: '14:00',
    email: 'tectum89@gmail.com',
    student_dni: '90107601',
    parent_name: 'Josselyn Margarita Jesús Hinostroza Cossio',
  },
  {
    student_name: 'Mijael Pedraza',
    end_date: '',
    days: 'L,X,V',
    start_time: '14:00',
    end_time: '15:00',
    email: 'teresa.160815@gmail.com',
    student_dni: '79250286',
    parent_name: 'Teresa Pedraza Bustamante',
  },
  {
    student_name: 'Gia Canales',
    end_date: '',
    days: 'L,M,X,J,V',
    start_time: '14:00',
    end_time: '15:00',
    email: 'trn_man@hotmail.com',
    student_dni: '90934863',
    parent_name: 'RENZO CANALES GALARRETA',
  },
  {
    student_name: 'Hannah Gutiérrez Ramos',
    end_date: '',
    days: 'M,J,V',
    start_time: '13:00',
    end_time: '14:00',
    email: 'xhans1830x@gmail.com',
    student_dni: '92445329',
    parent_name: 'Hans Elliott Gutierrez Guerrero',
  },
  {
    student_name: 'Giacomo Nevado',
    end_date: '',
    days: 'L,M,X,J,V',
    start_time: '18:00',
    end_time: '19:00',
    email: 'ymas162211@gmail.com',
    student_dni: '77990953',
    parent_name: 'Yovana Arteaga',
  },
  {
    student_name: 'Grace Paucar',
    end_date: '',
    days: 'L,M,X,J,V',
    start_time: '18:00',
    end_time: '19:00',
    email: 'yojanaper.202@gmail.com',
    student_dni: '78260797',
    parent_name: 'Elizabeth Zuñiga',
  },
  {
    student_name: 'Yoselyn Soledad',
    end_date: '',
    days: 'D',
    start_time: '13:00',
    end_time: '15:00',
    email: 'yosisanchezromero23@gmail.com',
    student_dni: '70053510',
    parent_name: 'Yo',
  },
  {
    student_name: 'Leandro Sánchez',
    end_date: '',
    days: 'D',
    start_time: '13:00',
    end_time: '15:00',
    email: 'yossy1893@gmail.com',
    student_dni: '73762867',
    parent_name: 'Yossy Ortiz Vásquez',
  },
  {
    student_name: 'Luna Bedon Cubas',
    end_date: '',
    days: 'L,X,V',
    start_time: '13:00',
    end_time: '14:00',
    email: 'yrenecubas1728@gmail.com',
    student_dni: '91947422',
    parent_name: 'Faustina Melo cazorla',
  },
  {
    student_name: 'Sofía Caupín Canchaya',
    end_date: '2025-02-28',
    days: 'L,X,V',
    start_time: '13:00',
    end_time: '14:00',
    email: '',
    student_dni: '',
    parent_name: '',
  },
  {
    student_name: 'Sebastian Recavarren',
    end_date: '2025-02-28',
    days: 'L,X,V',
    start_time: '13:00',
    end_time: '14:00',
    email: '',
    student_dni: '',
    parent_name: '',
  },
  {
    student_name: 'Santiago Malpartida',
    end_date: '2025-02-28',
    days: 'M,J',
    start_time: '13:00',
    end_time: '14:00',
    email: '',
    student_dni: '',
    parent_name: '',
  },
  {
    student_name: 'Leticia Geranimo Aurich',
    end_date: '',
    days: 'L,X,V',
    start_time: '14:00',
    end_time: '15:00',
    email: '',
    student_dni: '',
    parent_name: '',
  },
  {
    student_name: 'Adriano Huaman Fernandez',
    end_date: '',
    days: 'L,X,V',
    start_time: '14:00',
    end_time: '15:00',
    email: '',
    student_dni: '',
    parent_name: '',
  },
  {
    student_name: 'Sophie Valverde Nuñez',
    end_date: '',
    days: 'M,J',
    start_time: '18:00',
    end_time: '19:00',
    email: '',
    student_dni: '',
    parent_name: '',
  },
  {
    student_name: 'Diego Garces Rivera',
    end_date: '',
    days: 'M,J',
    start_time: '13:00',
    end_time: '14:00',
    email: '',
    student_dni: '',
    parent_name: '',
  },
  {
    student_name: 'Antonella Vargas',
    end_date: '',
    days: 'L,X,V',
    start_time: '13:00',
    end_time: '14:00',
    email: '',
    student_dni: '',
    parent_name: '',
  },
  {
    student_name: 'Niurka Aguayo',
    end_date: '',
    days: 'M,J',
    start_time: '13:00',
    end_time: '14:00',
    email: '',
    student_dni: '',
    parent_name: '',
  },
  {
    student_name: 'Thiago Abad',
    end_date: '',
    days: 'L,X,V',
    start_time: '14:00',
    end_time: '15:00',
    email: '',
    student_dni: '',
    parent_name: '',
  },
  {
    student_name: 'Mariana Antonella Ramos',
    end_date: '',
    days: 'M,V',
    start_time: '14:00',
    end_time: '15:00',
    email: '',
    student_dni: '',
    parent_name: '',
  },
  {
    student_name: 'Fabianna Arias',
    end_date: '',
    days: 'L,M,X,J,V',
    start_time: '18:00',
    end_time: '19:00',
    email: '',
    student_dni: '',
    parent_name: '',
  },
  {
    student_name: 'Alessandro Mamani',
    end_date: '',
    days: 'L,X,V',
    start_time: '14:00',
    end_time: '15:00',
    email: '',
    student_dni: '',
    parent_name: '',
  },
  {
    student_name: 'Yosster Sánchez Silva',
    end_date: '',
    days: 'L,X,V',
    start_time: '14:00',
    end_time: '15:00',
    email: '',
    student_dni: '',
    parent_name: '',
  },
  {
    student_name: 'Khalessi Alfaro',
    end_date: '',
    days: 'L,X,V',
    start_time: '13:00',
    end_time: '14:00',
    email: '',
    student_dni: '',
    parent_name: '',
  },
  {
    student_name: 'Josue Mamani',
    end_date: '',
    days: 'L,M,X,J,V',
    start_time: '18:00',
    end_time: '19:00',
    email: '',
    student_dni: '',
    parent_name: '',
  },
  {
    student_name: 'Thiago Perez',
    end_date: '',
    days: 'L,M,X,J,V',
    start_time: '18:00',
    end_time: '19:00',
    email: '',
    student_dni: '',
    parent_name: '',
  },
  {
    student_name: 'Samantha Lazo',
    end_date: '',
    days: 'L,X,V',
    start_time: '13:00',
    end_time: '14:00',
    email: '',
    student_dni: '',
    parent_name: '',
  },
  {
    student_name: 'Angelo Alburqueque',
    end_date: '',
    days: 'L,M,X,J,V',
    start_time: '18:00',
    end_time: '19:00',
    email: '',
    student_dni: '',
    parent_name: '',
  },
  {
    student_name: 'Kimberlyn Gómez',
    end_date: '',
    days: 'L,M,X,J,V',
    start_time: '18:00',
    end_time: '19:00',
    email: '',
    student_dni: '',
    parent_name: '',
  },
  {
    student_name: 'Mariana Arambulo',
    end_date: '',
    days: 'L,X,V',
    start_time: '13:00',
    end_time: '14:00',
    email: '',
    student_dni: '',
    parent_name: '',
  },
  {
    student_name: 'Alice Negreiros',
    end_date: '',
    days: 'L,X,V',
    start_time: '13:00',
    end_time: '14:00',
    email: '',
    student_dni: '',
    parent_name: '',
  },
  {
    student_name: 'Mathias Gabriel',
    end_date: '',
    days: 'L,X,V',
    start_time: '14:00',
    end_time: '15:00',
    email: '',
    student_dni: '',
    parent_name: '',
  },
  {
    student_name: 'Maximiliano Geal',
    end_date: '',
    days: 'L,X,V',
    start_time: '14:00',
    end_time: '15:00',
    email: '',
    student_dni: '',
    parent_name: '',
  },
];
